#!/bin/sh

config_ff_clients() {
	cat <<'EOM'
graph_title Number of Freifunk clients
graph_args --base 1000 -l 0
graph_vlabel number of Freifunk clients
graph_category freifunk
graph_info This graph shows the number of Freifunk clients connected.
clients.label clients
clients.draw LINE2
clients.info The current number of Freifunk clients.
EOM
}

fetch_ff_clients() {
  echo "clients.value" $(grep -Eo "\[.*\]+" /sys/kernel/debug/batman_adv/bat0/transtable_local|grep W|wc -l)
}


case $1 in
   config)
        config_ff_clients
	;;
   *)
	fetch_ff_clients
	;;
esac

